import type {
  DeliveryPartner,
  Order,
  Assignment,
  AssignmentMetrics,
} from "./types";

export const mockPartners: DeliveryPartner[] = [
  {
    id: "p1",
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "+1234567890",
    status: "ACTIVE",
    rating: 4.8,
    areas: "Downtown",
    shiftStart: "08:00",
    shiftEnd: "16:00",
    totalDeliveries: 245,
    successRate: 98,
  },
  {
    id: "p2",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    phone: "+1234567891",
    status: "INACTIVE",
    rating: 4.6,
    areas: "Uptown",
    shiftStart: "10:00",
    shiftEnd: "18:00",
    totalDeliveries: 189,
    successRate: 95,
  },
  {
    id: "p3",
    name: "Mike Johnson",
    email: "mike.johnson@example.com",
    phone: "+1234567892",
    status: "INACTIVE",
    rating: 4.2,
    areas: "Midtown",
    shiftStart: "12:00",
    shiftEnd: "20:00",
    totalDeliveries: 156,
    successRate: 92,
  },
  {
    id: "p4",
    name: "Sarah Williams",
    email: "sarah.williams@example.com",
    phone: "+1234567893",
    status: "ACTIVE",
    rating: 4.9,
    areas: "Westside",
    shiftStart: "09:00",
    shiftEnd: "17:00",
    totalDeliveries: 278,
    successRate: 99,
  },
  {
    id: "p5",
    name: "David Brown",
    email: "david.brown@example.com",
    phone: "+1234567894",
    status: "INACTIVE",
    rating: 4.5,
    areas: "Eastside",
    shiftStart: "11:00",
    shiftEnd: "19:00",
    totalDeliveries: 201,
    successRate: 94,
  },
];

export const mockOrders: Order[] = [
  {
    id: "o1",
    orderNumber: "ORD-001",
    customerName: "Alice Cooper",
    customerAddress: "123 Main St, Downtown",
    area: "Downtown",
    status: "PENDING",
    scheduledTime: "2023-05-15T10:30:00",
    totalAmount: 45.99,
    items: 3,
  },
  {
    id: "o2",
    orderNumber: "ORD-002",
    customerName: "Bob Marley",
    customerAddress: "456 Oak Ave, Uptown",
    area: "Uptown",
    status: "IN_PROGRESS",
    scheduledTime: "2023-05-15T11:15:00",
    totalAmount: 32.5,
    items: 2,
    partnerId: "p2",
  },
  {
    id: "o3",
    orderNumber: "ORD-003",
    customerName: "Charlie Puth",
    customerAddress: "789 Pine Rd, Midtown",
    area: "Midtown",
    status: "COMPLETED",
    scheduledTime: "2023-05-15T09:45:00",
    totalAmount: 78.25,
    items: 5,
    partnerId: "p3",
  },
  {
    id: "o4",
    orderNumber: "ORD-004",
    customerName: "Diana Ross",
    customerAddress: "101 Elm Blvd, Westside",
    area: "Westside",
    status: "CANCELLED",
    scheduledTime: "2023-05-15T12:00:00",
    totalAmount: 25.99,
    items: 1,
    partnerId: "p4",
  },
  {
    id: "o5",
    orderNumber: "ORD-005",
    customerName: "Edward Norton",
    customerAddress: "202 Maple Dr, Eastside",
    area: "Eastside",
    status: "PENDING",
    scheduledTime: "2023-05-15T13:30:00",
    totalAmount: 56.75,
    items: 4,
  },
];

export const mockAssignments: Assignment[] = [
  {
    id: "a1",
    orderId: "o2",
    orderNumber: "ORD-002",
    partnerId: "p2",
    partnerName: "Jane Smith",
    status: "ACCEPTED",
    assignedTime: "2023-05-15T11:00:00",
    estimatedDeliveryTime: "2023-05-15T11:45:00",
  },
  {
    id: "a2",
    orderId: "o3",
    orderNumber: "ORD-003",
    partnerId: "p3",
    partnerName: "Mike Johnson",
    status: "ACCEPTED",
    assignedTime: "2023-05-15T09:30:00",
    estimatedDeliveryTime: "2023-05-15T10:15:00",
    actualDeliveryTime: "2023-05-15T10:10:00",
  },
  {
    id: "a3",
    orderId: "o4",
    orderNumber: "ORD-004",
    partnerId: "p4",
    partnerName: "Sarah Williams",
    status: "PENDING",
    assignedTime: "2023-05-15T11:45:00",
    estimatedDeliveryTime: "2023-05-15T12:30:00",
  },
];

export const mockAssignmentMetrics: AssignmentMetrics = {
  totalAssigned: 156,
  successRate: 92,
  averageDeliveryTime: "28 mins",
  failureReasons: [
    { reason: "Partner unavailable", count: 12 },
    { reason: "Customer not available", count: 8 },
    { reason: "Wrong address", count: 5 },
    { reason: "Technical issues", count: 3 },
  ],
};

export const mockPartnersMetrics = {
  totalActive: 32,
  avgRating: 4.6,
  topAreas: ["Downtown", "Uptown", "Midtown"],
};

export const mockPartnerAvailability = {
  available: 18,
  busy: 14,
  offline: 8,
};
